### ISSUE TITLE
use `do.call()`

### ISSUE THREAD

**Issue by mammykins** [mammykins/blockbuster#27]
see Rchaeology pdf, this should speed up repeated `rbind()`

**Comment by ivyleavedtoadflax** [comment]
Think I'm going to blog about do.call etc. They are quite core to the language, and I never use them.

**Comment by mammykins** [comment]
Reading Rchaelogy made me feel bad, need to go through and implement some advanced R

**Comment by ivyleavedtoadflax** [comment]
Beware premature optimisation! Get it working first, then iterate over it as required.

**Comment by mammykins** [comment]
Not required
