### ISSUE TITLE
Test builds on exact R versions used in DfE

### ISSUE THREAD

**Issue by ivyleavedtoadflax** [mammykins/blockbuster#33]
I've just started to build on a number of R versions, think you should work out which version DfE is using, and test this R version specifically.

More information here : https://docs.travis-ci.com/user/languages/r/
My example: https://github.com/ukgovdatascience/eesectors/commit/6c1508e94c0a7e727cdfc4a404141312c3f1e24a

Note travis is still disrupted at present: https://www.traviscistatus.com/

**Comment by mammykins** [comment]
Both are using "Sincere Pumpkin Patch"

**Comment by ivyleavedtoadflax** [comment]
Once you are not actively developing this so much, I would consider moving to a `.travis.yml` more like https://github.com/ukgovdatascience/govstyle/blob/update/relaxdepends/.travis.yml. This will conduct more tests, and will therefore take longer to complete, but it will help to highlight problems sooner. The same can be done for appveyor, but I have not yet implemented this.

**Comment by ivyleavedtoadflax** [comment]
Also it would be good to add an appveyor shield to the README.
