### ISSUE TITLE
areafy function hard to read

### ISSUE THREAD

**Issue by mammykins** [mammykins/blockbuster#36]
This was developed when I was new to string handling, there's better human readable ways to do this that I've discovered since. Revisit and improve. This is important as it provides the initial area estimates for time zero of the school estate.

**Comment by ivyleavedtoadflax** [comment]
e.g.:

<img width="1440" alt="screen shot 2017-03-01 at 10 31 38" src="https://cloud.githubusercontent.com/assets/4583655/23456196/58b7e482-fe6a-11e6-92ad-3c8c427a73c6.png">

**Comment by mammykins** [comment]
Fixed, see `areafy2` which uses `case_when` from `dplyr`
